CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Brands" (
    "BrandId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    CONSTRAINT "PK_Brands" PRIMARY KEY ("BrandId")
);

CREATE TABLE "Categories" (
    "CategoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryName" character varying(50) NOT NULL,
    "ParentCategoryId" integer NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryId"),
    CONSTRAINT "FK_Categories_Categories_ParentCategoryId" FOREIGN KEY ("ParentCategoryId") REFERENCES "Categories" ("CategoryId") ON DELETE CASCADE
);

CREATE TABLE "Colors" (
    "ColorId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ColorName" character varying(50) NOT NULL,
    CONSTRAINT "PK_Colors" PRIMARY KEY ("ColorId")
);

CREATE TABLE "OrderTransactions" (
    "OrderId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TransactionStatus" integer NOT NULL,
    "Transaction Updated At" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OrderTransactions" PRIMARY KEY ("OrderId")
);

CREATE TABLE "Sections" (
    "SectionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "SectionName" character varying(50) NOT NULL,
    CONSTRAINT "PK_Sections" PRIMARY KEY ("SectionId")
);

CREATE TABLE "Sizes" (
    "SizeId" integer GENERATED BY DEFAULT AS IDENTITY,
    "SizeName" character varying(50) NOT NULL,
    CONSTRAINT "PK_Sizes" PRIMARY KEY ("SizeId")
);

CREATE TABLE "Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserType" integer NOT NULL,
    "UserEmail" character varying(50) NOT NULL,
    "UserPassword" character varying(50) NOT NULL,
    "UserPhone" character varying(50) NOT NULL,
    "UserFirstName" character varying(50) NOT NULL,
    "UserLastName" character varying(50) NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);

CREATE TABLE "Products" (
    "ProductId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "BrandId" integer NOT NULL,
    "Price" integer NOT NULL,
    "Raiting" real NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("ProductId"),
    CONSTRAINT "FK_Products_Brands_BrandId" FOREIGN KEY ("BrandId") REFERENCES "Brands" ("BrandId") ON DELETE CASCADE,
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId") ON DELETE CASCADE
);

CREATE TABLE "SectionCategories" (
    "CategoryId" integer NOT NULL,
    "SectionId" integer NOT NULL,
    CONSTRAINT "PK_SectionCategories" PRIMARY KEY ("SectionId", "CategoryId"),
    CONSTRAINT "FK_SectionCategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId") ON DELETE CASCADE,
    CONSTRAINT "FK_SectionCategories_Sections_SectionId" FOREIGN KEY ("SectionId") REFERENCES "Sections" ("SectionId") ON DELETE CASCADE
);

CREATE TABLE "Addresses" (
    "AddressId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Address" varchar(50) NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("AddressId"),
    CONSTRAINT "FK_Addresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "CardItems" (
    "ProductVariantId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Quantity" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_CardItems" PRIMARY KEY ("ProductVariantId"),
    CONSTRAINT "FK_CardItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Medias" (
    "MediaId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "MediaFileType" character varying(50) NOT NULL,
    "MediaFileName" character varying(50) NOT NULL,
    "MediaBytes" character varying(50) NOT NULL,
    CONSTRAINT "PK_Medias" PRIMARY KEY ("MediaId"),
    CONSTRAINT "FK_Medias_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("ProductId") ON DELETE CASCADE
);

CREATE TABLE "Reviews" (
    "ReviewId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "ReviewTitle" character varying(50) NOT NULL,
    "ReviewRaing" integer NOT NULL,
    "ReviewComment" character varying(2000) NOT NULL,
    "ReviewCreatedAt" timestamp with time zone NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("ReviewId"),
    CONSTRAINT "FK_Reviews_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("ProductId") ON DELETE CASCADE,
    CONSTRAINT "FK_Reviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Orders" (
    "OrderId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Price" integer NOT NULL,
    "AddressId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "OrderStatus" integer NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("OrderId"),
    CONSTRAINT "FK_Orders_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("AddressId") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_OrderTransactions_OrderId" FOREIGN KEY ("OrderId") REFERENCES "OrderTransactions" ("OrderId") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "ProductVariants" (
    "ProductVariantId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "SizeId" integer NOT NULL,
    "ColorId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Sku" character varying(50) NOT NULL,
    CONSTRAINT "PK_ProductVariants" PRIMARY KEY ("ProductVariantId"),
    CONSTRAINT "FK_ProductVariants_CardItems_ProductId" FOREIGN KEY ("ProductId") REFERENCES "CardItems" ("ProductVariantId") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductVariants_Colors_ColorId" FOREIGN KEY ("ColorId") REFERENCES "Colors" ("ColorId") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductVariants_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("ProductId") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductVariants_Sizes_SizeId" FOREIGN KEY ("SizeId") REFERENCES "Sizes" ("SizeId") ON DELETE CASCADE
);

CREATE TABLE "OrderItems" (
    "ProductVariantId" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_OrderItems" PRIMARY KEY ("ProductVariantId"),
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("OrderId") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderItems_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("ProductVariantId") ON DELETE CASCADE
);

CREATE INDEX "IX_Addresses_UserId" ON "Addresses" ("UserId");

CREATE INDEX "IX_CardItems_UserId" ON "CardItems" ("UserId");

CREATE INDEX "IX_Categories_ParentCategoryId" ON "Categories" ("ParentCategoryId");

CREATE INDEX "IX_Medias_ProductId" ON "Medias" ("ProductId");

CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");

CREATE INDEX "IX_Orders_AddressId" ON "Orders" ("AddressId");

CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");

CREATE INDEX "IX_Products_BrandId" ON "Products" ("BrandId");

CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");

CREATE INDEX "IX_ProductVariants_ColorId" ON "ProductVariants" ("ColorId");

CREATE UNIQUE INDEX "IX_ProductVariants_ProductId" ON "ProductVariants" ("ProductId");

CREATE INDEX "IX_ProductVariants_SizeId" ON "ProductVariants" ("SizeId");

CREATE INDEX "IX_Reviews_ProductId" ON "Reviews" ("ProductId");

CREATE INDEX "IX_Reviews_UserId" ON "Reviews" ("UserId");

CREATE INDEX "IX_SectionCategories_CategoryId" ON "SectionCategories" ("CategoryId");

CREATE UNIQUE INDEX "IX_SectionCategories_SectionId" ON "SectionCategories" ("SectionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240309142527_Initilize', '7.0.16');

COMMIT;

