/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 26-окт-2023 0:11:01 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS addresses CASCADE
;

DROP TABLE IF EXISTS brand CASCADE
;

DROP TABLE IF EXISTS cart_item CASCADE
;

DROP TABLE IF EXISTS category CASCADE
;

DROP TABLE IF EXISTS color CASCADE
;

DROP TABLE IF EXISTS media CASCADE
;

DROP TABLE IF EXISTS "order" CASCADE
;

DROP TABLE IF EXISTS order_items CASCADE
;

DROP TABLE IF EXISTS order_transactions CASCADE
;

DROP TABLE IF EXISTS product CASCADE
;

DROP TABLE IF EXISTS product_variant CASCADE
;

DROP TABLE IF EXISTS review CASCADE
;

DROP TABLE IF EXISTS section_category CASCADE
;

DROP TABLE IF EXISTS sections CASCADE
;

DROP TABLE IF EXISTS size CASCADE
;

DROP TABLE IF EXISTS "user" CASCADE
;

/* Create Tables */

CREATE TABLE addresses
(
	a_id integer NOT NULL,
	a_user_id integer NOT NULL,
	a_adresses varchar(50) NOT NULL
)
;

CREATE TABLE brand
(
	b_id integer NOT NULL,
	b_name varchar(50) NOT NULL
)
;

CREATE TABLE cart_item
(
	ci_product_variant_id integer NOT NULL,
	ci_user_id integer NOT NULL,
	quantity integer NOT NULL
)
;

CREATE TABLE category
(
	c_id integer NOT NULL,
	c_parent_category_id integer NOT NULL,
	c_name varchar(50) NOT NULL
)
;

CREATE TABLE color
(
	c_id integer NOT NULL,
	c_name varchar(50) NOT NULL
)
;

CREATE TABLE media
(
	m_id integer NOT NULL,
	m_product_id integer NOT NULL,
	m_bytes bytea NOT NULL,
	m_file_type varchar(50) NOT NULL,
	m_file_name varchar(50) NOT NULL
)
;

CREATE TYPE statuses as enum('in proccesing', 'in delivery','completed', 'finished');

CREATE TABLE "order"
(
	o_id integer NOT NULL,
	o_user_id integer NOT NULL,
	o_price integer NOT NULL,
	o_address_id integer NOT NULL,
	o_created_at date NOT NULL,
	o_order_status statuses NOT NULL  
)
;

CREATE TABLE order_items
(
	oi_product_variant_id integer NOT NULL,
	oi_order_id integer NOT NULL,
	oi_quantity integer NOT NULL
)
;

CREATE TABLE order_transactions
(
	ot_o_id integer NOT NULL,
	ot_status statuses NOT NULL, 
	ot_updated_at date NOT NULL
)
;

CREATE TABLE product
(
	p_id integer NOT NULL,
	p_brand_id integer NOT NULL,
	p_category_id integer NOT NULL,
	p_name varchar(50) NOT NULL,
	p_price integer NOT NULL,
	p_variant_id integer NOT NULL,
	p_average_raiting integer NOT NULL
)
;

CREATE TABLE product_variant
(
	pv_id integer NOT NULL,
	pv_color_id integer NOT NULL,
	pv_size_id integer NOT NULL,
	pv_product_id integer NOT NULL,
	pv_quantity integer NOT NULL,
	pv_sku varchar(50) NOT NULL
)
;

CREATE TABLE review
(
	r_id integer NOT NULL,
	r_product_id integer NULL,
	r_user_id integer NULL,
	r_raiting integer NULL,
	r_title varchar(50) NULL,
	r_comment varchar(2000) NULL,
	r_created_at date NULL
)
;

CREATE TABLE section_category
(
	sc_category_id integer NOT NULL,
	sc_section_id integer NOT NULL
)
;

CREATE TABLE sections
(
	s_id integer NOT NULL,
	s_name varchar(50) NOT NULL
)
;

CREATE TABLE size
(
	s_id integer NOT NULL,
	s_name varchar(50) NOT NULL
)
;
CREATE TYPE users as enum('admin', 'user');

CREATE TABLE "user"
(
	u_id integer NOT NULL,
	u_type users NOT NULL,           
	u_email varchar(50) NOT NULL,
	u_password varchar(50) NOT NULL,
	u_phone varchar(50) NOT NULL,
	u_first_name varchar(50) NOT NULL,
	u_last_name varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE addresses ADD CONSTRAINT "PK_addresses"
	PRIMARY KEY (a_id)
;

CREATE INDEX "IXFK_addresses_user" ON addresses (a_user_id ASC)
;

ALTER TABLE brand ADD CONSTRAINT "PK_brand"
	PRIMARY KEY (b_id)
;

ALTER TABLE cart_item ADD CONSTRAINT "PK_cart_item"
	PRIMARY KEY (ci_product_variant_id)
;

CREATE INDEX "IXFK_cart_item_product_variant" ON cart_item (ci_product_variant_id ASC)
;

CREATE INDEX "IXFK_cart_item_user" ON cart_item (ci_user_id ASC)
;

ALTER TABLE category ADD CONSTRAINT "PK_category"
	PRIMARY KEY (c_id)
;

CREATE INDEX "IXFK_category_category" ON category (c_id ASC)
;

ALTER TABLE color ADD CONSTRAINT "PK_color"
	PRIMARY KEY (c_id)
;

ALTER TABLE media ADD CONSTRAINT "PK_media"
	PRIMARY KEY (m_id)
;

CREATE INDEX "IXFK_media_product" ON media (m_product_id ASC)
;

ALTER TABLE "order" ADD CONSTRAINT "PK_order"
	PRIMARY KEY (o_id)
;

CREATE INDEX "IXFK_order_addresses" ON "order" (o_address_id ASC)
;

CREATE INDEX "IXFK_order_user" ON "order" (o_user_id ASC)
;

ALTER TABLE order_items ADD CONSTRAINT "PK_order_items"
	PRIMARY KEY (oi_product_variant_id)
;

CREATE INDEX "IXFK_order_items_order" ON order_items (oi_order_id ASC)
;

CREATE INDEX "IXFK_order_items_product_variant" ON order_items (oi_product_variant_id ASC)
;

ALTER TABLE order_transactions ADD CONSTRAINT "PK_order_transactions"
	PRIMARY KEY (ot_o_id)
;

CREATE INDEX "IXFK_order_transactions_order" ON order_transactions (ot_o_id ASC)
;

ALTER TABLE product ADD CONSTRAINT "PK_Table A"
	PRIMARY KEY (p_id)
;

CREATE INDEX "IXFK_product_brand" ON product (p_brand_id ASC)
;

CREATE INDEX "IXFK_product_category" ON product (p_category_id ASC)
;

ALTER TABLE product_variant ADD CONSTRAINT "PK_product_variant"
	PRIMARY KEY (pv_id)
;

CREATE INDEX "IXFK_product_variant_color" ON product_variant (pv_color_id ASC)
;

CREATE INDEX "IXFK_product_variant_product" ON product_variant (pv_product_id ASC)
;

CREATE INDEX "IXFK_product_variant_size" ON product_variant (pv_size_id ASC)
;

ALTER TABLE review ADD CONSTRAINT "PK_review"
	PRIMARY KEY (r_id)
;

CREATE INDEX "IXFK_review_product" ON review (r_product_id ASC)
;

CREATE INDEX "IXFK_review_user" ON review (r_user_id ASC)
;

ALTER TABLE section_category ADD CONSTRAINT "PK_section_category"
	PRIMARY KEY ()
;

CREATE INDEX "IXFK_section_category_category" ON section_category (sc_category_id ASC)
;

CREATE INDEX "IXFK_section_category_sections" ON section_category (sc_section_id ASC)
;

ALTER TABLE sections ADD CONSTRAINT "PK_sections"
	PRIMARY KEY (s_id)
;

ALTER TABLE size ADD CONSTRAINT "PK_size"
	PRIMARY KEY (s_id)
;

ALTER TABLE "user" ADD CONSTRAINT "PK_user"
	PRIMARY KEY (u_id)
;

/* Create Foreign Key Constraints */

ALTER TABLE addresses ADD CONSTRAINT "FK_addresses_user"
	FOREIGN KEY (a_user_id) REFERENCES "user" (u_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cart_item ADD CONSTRAINT "FK_cart_item_product_variant"
	FOREIGN KEY (ci_product_variant_id) REFERENCES product_variant (pv_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cart_item ADD CONSTRAINT "FK_cart_item_user"
	FOREIGN KEY (ci_user_id) REFERENCES "user" (u_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE media ADD CONSTRAINT "FK_media_product"
	FOREIGN KEY (m_product_id) REFERENCES product (p_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "order" ADD CONSTRAINT "FK_order_addresses"
	FOREIGN KEY (o_address_id) REFERENCES addresses (a_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "order" ADD CONSTRAINT "FK_order_user"
	FOREIGN KEY (o_user_id) REFERENCES "user" (u_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE order_items ADD CONSTRAINT "FK_order_items_order"
	FOREIGN KEY (oi_order_id) REFERENCES "order" (o_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE order_items ADD CONSTRAINT "FK_order_items_product_variant"
	FOREIGN KEY (oi_product_variant_id) REFERENCES product_variant (pv_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE order_transactions ADD CONSTRAINT "FK_order_transactions_order"
	FOREIGN KEY (ot_o_id) REFERENCES "order" (o_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product ADD CONSTRAINT "FK_product_brand"
	FOREIGN KEY (p_brand_id) REFERENCES brand (b_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product ADD CONSTRAINT "FK_product_category"
	FOREIGN KEY (p_category_id) REFERENCES category (c_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product_variant ADD CONSTRAINT "FK_product_variant_color"
	FOREIGN KEY (pv_color_id) REFERENCES color (c_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product_variant ADD CONSTRAINT "FK_product_variant_product"
	FOREIGN KEY (pv_product_id) REFERENCES product (p_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product_variant ADD CONSTRAINT "FK_product_variant_size"
	FOREIGN KEY (pv_size_id) REFERENCES size (s_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE review ADD CONSTRAINT "FK_review_product"
	FOREIGN KEY (r_product_id) REFERENCES product (p_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE review ADD CONSTRAINT "FK_review_user"
	FOREIGN KEY (r_user_id) REFERENCES "user" (u_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE section_category ADD CONSTRAINT "FK_section_category_category"
	FOREIGN KEY (sc_category_id) REFERENCES category (c_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE section_category ADD CONSTRAINT "FK_section_category_sections"
	FOREIGN KEY (sc_section_id) REFERENCES sections (s_id) ON DELETE No Action ON UPDATE No Action
;
